version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-northeast-1"
profile = "Genki0913-root"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "genki-verification"
s3_prefix = "deploy"
profile = "Genki0913-root"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []