AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 検証

Globals:
  Function:
    Timeout: 10

Resources:
  SqsProducer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sqs-producer
      CodeUri: sqs-producer
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt FifoQueue.QueueName
      Environment:
        Variables:
          SQSQueueUrl: !Ref FifoQueue

  SqsConsumer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sqs-consumer
      CodeUri: sqs-consumer
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Events:
        SampleSqs:
          Type: SQS
          Properties:
            Enabled: true
            Queue: !GetAtt FifoQueue.Arn
            BatchSize: 5
            FunctionResponseTypes:
              - ReportBatchItemFailures

  FifoQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true
      QueueName: FifoQueue.fifo
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt FifoDLQueue.Arn
        maxReceiveCount: 2
      VisibilityTimeout: 20
      ReceiveMessageWaitTimeSeconds: 5
    DependsOn: FifoDLQueue
  FifoDLQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: false
      FifoQueue: true
      QueueName: FifoDLQueue.fifo
      VisibilityTimeout: 30
